version: '3.4'
services:
  invoicing:
    image: megednazednav/invoicing:0.1.6
    volumes:
     - ./data/invoicing:/usr/src/app/db/data
  invoicing-sync:
    image: megednazednav/invoicing-sync:0.1.5
    volumes:
      - ./data/invoicing-sync/credentials.json:/app/credentials.json
