version: '3.4'
services:
  cronjobs:
    image: megednazednav/cronjob-invoicing:0.0.3
    build: ./config/cron/
    volumes:
      - ./data:/data
      - ./config/cron/cronjobs:/etc/crontabs/root
      - ./config/cron/scripts:/scripts
  invoicing:
    image: megednazednav/invoicing:0.3.0
    volumes:
     - ./data/invoicing:/usr/src/app/db/data
  invoicing-sync:
    image: megednazednav/invoicing-sync:0.1.5
    volumes:
      - ./data/invoicing-sync/credentials.json:/app/credentials.json
